services:
  db:
    image: postgres:16
    container_name: project-soeun-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: project_soeun
      POSTGRES_USER: soeun
      POSTGRES_PASSWORD: soeun_pw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
