spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_soeun
    username: soeun
    password: soeun_pw

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

server:
  port: 8080
